# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "f6818c953f3b58ac8774351ea195640b15ddf2fc"

[[deps.AntiRheumaticDrugs]]
deps = ["DrugInterface"]
path = "."
uuid = "7123f3dd-e172-456f-9a19-c2b7ef93fd76"
version = "0.1.0"

[[deps.DrugInterface]]
git-tree-sha1 = "77cc4b5890946738358a89a2f611c64473e3f4b9"
repo-rev = "main"
repo-url = "https://github.com/simonsteiger/DrugInterface.jl"
uuid = "ecbac44d-373e-48a5-bcbb-08f349367545"
version = "0.1.0"
